- hosts: all
  become: yes
  gather_facts: yes

#  pre_tasks:
#    - name: create docker environment file
#      file: path=/etc/default/docker state=touch
#
#    - name: add DOCKER_OPTS
#      lineinfile:
#        path: /etc/default/docker
#        line: 'DOCKER_OPTS='

  roles:
    - ansible-role-rhn
#    - role: grycap.docker
#      docker_start_service: true
#      docker_opts: "--insecure-registry 172.30.0.0/16 --insecure-registry local.openshift"

  post_tasks:
    - name: install packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      - PyYAML
      - python-devel
      - openssl-devel
      - git
      ignore_errors: true

    - name: install docker
      yum:
        name: docker
        state: present

    - name: enable to insecure registry
      lineinfile:
        dest: /etc/sysconfig/docker
        insertafter: "^# INSECURE_REGISTRY="
        line: "INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16 --insecure-registry local.openshift'"

    - name: restart docker
      service:
        name: docker
        state: restarted

    - name: install more packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
      - python-pip

    - name: pip upgrade setuptools and pip
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
      - pip
      - setuptools
      - virtualenv

    - name: install ansible
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
      - ansible

    - name: install ansible-container into virtualenv
      pip:
        name: git+https://github.com/oatakan/ansible-container#egg=master
        virtualenv: /root/venv

- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - role: cluster-up-role
      openshift_github_user: openshift
      openshift_github_name: origin
      openshift_github_url: https://api.github.com/repos
      openshift_release_tag_name: "v1.5.0"
      openshift_client_dest: /usr/local/bin
      openshift_force_client_install: yes
      openshift_volume_name: project-data
      openshift_volume_path: "{{ lookup('env','HOME') }}/volumes/project/data"
      openshift_hostname: local.openshift
      openshift_recreate: yes