- hosts: all
  become: yes
  gather_facts: yes
  roles:
    - ansible-role-rhn
    - indigo-dc.docker
    - chouseknecht.cluster-up-role
      openshift_github_user: openshift
      openshift_github_name: origin
      openshift_github_url: https://api.github.com/repos
      openshift_release_tag_name: "v1.5.0"
      openshift_client_dest: /usr/local/bin
      openshift_force_client_install: yes
      openshift_volume_name: project-data
      openshift_volume_path: "{{ lookup('env','HOME') }}/volumes/project/data"
      openshift_hostname: local.openshift
      openshift_recreate: yes